package dev.JustRed23.grandfather.command.handler;

public enum CheckTypes {
    BOT_NOT_CONNECTED,
    BOT_NO_PERMISSION,
    CANNOT_DETECT_STATE,
    COMMAND_NOT_FOUND,
    COMMAND_NO_PERMISSION,
    EMPTY_QUEUE,
    IN_DIFFERENT_CHANNEL,
    NOT_PLAYING,
    SUCCESS,
    SUPPRESSED_FAIL,
    USER_NOT_CONNECTED
}
